// Code generated by MockGen. DO NOT EDIT.
// Source: F:\shorturl\internal\storages\filestorage\filestorage.go

// Package filestorage is a generated GoMock package.
package filestorage

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// AppendToFile mocks base method.
func (m *MockStorage) AppendToFile(data URLData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendToFile", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendToFile indicates an expected call of AppendToFile.
func (mr *MockStorageMockRecorder) AppendToFile(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendToFile", reflect.TypeOf((*MockStorage)(nil).AppendToFile), data)
}

// GetURL mocks base method.
func (m *MockStorage) GetURL(shortURL string) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURL", shortURL)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetURL indicates an expected call of GetURL.
func (mr *MockStorageMockRecorder) GetURL(shortURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURL", reflect.TypeOf((*MockStorage)(nil).GetURL), shortURL)
}

// LoadFromFile mocks base method.
func (m *MockStorage) LoadFromFile() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadFromFile")
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadFromFile indicates an expected call of LoadFromFile.
func (mr *MockStorageMockRecorder) LoadFromFile() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadFromFile", reflect.TypeOf((*MockStorage)(nil).LoadFromFile))
}

// SetURL mocks base method.
func (m *MockStorage) SetURL(uuid, shortURL, originalURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetURL", uuid, shortURL, originalURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetURL indicates an expected call of SetURL.
func (mr *MockStorageMockRecorder) SetURL(uuid, shortURL, originalURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetURL", reflect.TypeOf((*MockStorage)(nil).SetURL), uuid, shortURL, originalURL)
}
